// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEvent {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sha256: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub pid: u32,
    #[prost(uint32, tag = "4")]
    pub uid: u32,
    #[prost(enumeration = "FileOp", tag = "5")]
    pub operation: i32,
    /// Unix ms
    #[prost(int64, tag = "6")]
    pub timestamp: i64,
    /// Shannon entropy of file content
    #[prost(float, tag = "7")]
    pub entropy: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcEvent {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    #[prost(uint32, tag = "2")]
    pub ppid: u32,
    #[prost(uint32, tag = "3")]
    pub uid: u32,
    #[prost(string, tag = "4")]
    pub comm: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub cmdline: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub exe_path: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub timestamp: i64,
    /// execve | clone | ptrace | mmap
    #[prost(string, tag = "8")]
    pub syscall: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetEvent {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    #[prost(string, tag = "2")]
    pub src_ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub src_port: u32,
    #[prost(string, tag = "4")]
    pub dst_ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub dst_port: u32,
    /// tcp | udp
    #[prost(string, tag = "6")]
    pub proto: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub dns_query: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub tls_sni: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub bytes_out: u64,
    #[prost(int64, tag = "10")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemEvent {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    #[prost(string, tag = "2")]
    pub region: ::prost::alloc::string::String,
    /// executable anonymous mapping
    #[prost(bool, tag = "3")]
    pub exec_anon: bool,
    #[prost(bool, tag = "4")]
    pub heap_exec: bool,
    #[prost(string, tag = "5")]
    pub injected_lib: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileBurstEvent {
    #[prost(string, tag = "1")]
    pub base_path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub count: u32,
    /// avg entropy increase per file
    #[prost(float, tag = "3")]
    pub entropy_delta: f32,
    #[prost(enumeration = "AgentType", tag = "4")]
    pub source: i32,
    #[prost(int64, tag = "5")]
    pub window_start_ts: i64,
    #[prost(int64, tag = "6")]
    pub window_end_ts: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcBurstEvent {
    #[prost(uint32, tag = "1")]
    pub ppid: u32,
    #[prost(string, tag = "2")]
    pub parent_comm: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub child_count: u32,
    #[prost(int64, tag = "4")]
    pub window_start_ts: i64,
    #[prost(int64, tag = "5")]
    pub window_end_ts: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreatSignal {
    #[prost(enumeration = "AgentType", tag = "1")]
    pub source: i32,
    /// 0.0 – 1.0
    #[prost(float, tag = "2")]
    pub confidence: f32,
    #[prost(uint32, tag = "3")]
    pub ttl_seconds: u32,
    /// Unix ms
    #[prost(int64, tag = "4")]
    pub ts: i64,
    #[prost(oneof = "threat_signal::Event", tags = "10, 11, 12, 13, 14, 15")]
    pub event: ::core::option::Option<threat_signal::Event>,
}
/// Nested message and enum types in `ThreatSignal`.
pub mod threat_signal {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "10")]
        FileEvent(super::FileEvent),
        #[prost(message, tag = "11")]
        ProcEvent(super::ProcEvent),
        #[prost(message, tag = "12")]
        NetEvent(super::NetEvent),
        #[prost(message, tag = "13")]
        MemEvent(super::MemEvent),
        #[prost(message, tag = "14")]
        FileBurst(super::FileBurstEvent),
        #[prost(message, tag = "15")]
        ProcBurst(super::ProcBurstEvent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreatVerdict {
    #[prost(string, tag = "1")]
    pub verdict_id: ::prost::alloc::string::String,
    #[prost(enumeration = "Verdict", tag = "2")]
    pub verdict: i32,
    #[prost(float, tag = "3")]
    pub risk_score: f32,
    #[prost(float, tag = "4")]
    pub sig_confidence: f32,
    #[prost(float, tag = "5")]
    pub beh_confidence: f32,
    #[prost(float, tag = "6")]
    pub ml_confidence: f32,
    #[prost(float, tag = "7")]
    pub box_confidence: f32,
    /// comma-separated MITRE IDs triggered
    #[prost(string, tag = "8")]
    pub rule_ids: ::prost::alloc::string::String,
    #[prost(int64, tag = "9")]
    pub ts: i64,
    #[prost(string, tag = "10")]
    pub subject_path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "11")]
    pub subject_pid: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActionRequest {
    #[prost(string, tag = "1")]
    pub verdict_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub verdict: ::core::option::Option<ThreatVerdict>,
    #[prost(enumeration = "ResponseMode", tag = "3")]
    pub mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActionResult {
    #[prost(string, tag = "1")]
    pub verdict_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub executed: bool,
    /// kill | hard_quarantine | soft_quarantine | block_net | monitor
    #[prost(string, tag = "3")]
    pub action_taken: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub user_approved: bool,
    #[prost(int64, tag = "5")]
    pub ts: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(bool, tag = "1")]
    pub queen_alive: bool,
    #[prost(uint32, tag = "2")]
    pub active_agents: u32,
    #[prost(uint64, tag = "3")]
    pub events_today: u64,
    #[prost(uint32, tag = "4")]
    pub threats_active: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListThreatsRequest {
    #[prost(uint32, tag = "1")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListThreatsResponse {
    #[prost(message, repeated, tag = "1")]
    pub verdicts: ::prost::alloc::vec::Vec<ThreatVerdict>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OverrideRequest {
    #[prost(string, tag = "1")]
    pub verdict_id: ::prost::alloc::string::String,
    #[prost(enumeration = "Verdict", tag = "2")]
    pub new_verdict: i32,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OverrideResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExportRequest {
    #[prost(int64, tag = "1")]
    pub since_ts: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntry {
    #[prost(string, tag = "1")]
    pub line: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub ts: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentType {
    AgentUnknown = 0,
    AgentFile = 1,
    AgentProc = 2,
    AgentNet = 3,
    AgentMem = 4,
}
impl AgentType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AgentUnknown => "AGENT_UNKNOWN",
            Self::AgentFile => "AGENT_FILE",
            Self::AgentProc => "AGENT_PROC",
            Self::AgentNet => "AGENT_NET",
            Self::AgentMem => "AGENT_MEM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGENT_UNKNOWN" => Some(Self::AgentUnknown),
            "AGENT_FILE" => Some(Self::AgentFile),
            "AGENT_PROC" => Some(Self::AgentProc),
            "AGENT_NET" => Some(Self::AgentNet),
            "AGENT_MEM" => Some(Self::AgentMem),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileOp {
    Unknown = 0,
    FileCreate = 1,
    FileWrite = 2,
    FileRename = 3,
    FileDelete = 4,
    FileChmod = 5,
}
impl FileOp {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "FILE_OP_UNKNOWN",
            Self::FileCreate => "FILE_CREATE",
            Self::FileWrite => "FILE_WRITE",
            Self::FileRename => "FILE_RENAME",
            Self::FileDelete => "FILE_DELETE",
            Self::FileChmod => "FILE_CHMOD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FILE_OP_UNKNOWN" => Some(Self::Unknown),
            "FILE_CREATE" => Some(Self::FileCreate),
            "FILE_WRITE" => Some(Self::FileWrite),
            "FILE_RENAME" => Some(Self::FileRename),
            "FILE_DELETE" => Some(Self::FileDelete),
            "FILE_CHMOD" => Some(Self::FileChmod),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Verdict {
    Unknown = 0,
    /// score < 0.35
    Clean = 1,
    /// score 0.35..0.70
    Quarantine = 2,
    /// score > 0.70
    Kill = 3,
}
impl Verdict {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "VERDICT_UNKNOWN",
            Self::Clean => "VERDICT_CLEAN",
            Self::Quarantine => "VERDICT_QUARANTINE",
            Self::Kill => "VERDICT_KILL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VERDICT_UNKNOWN" => Some(Self::Unknown),
            "VERDICT_CLEAN" => Some(Self::Clean),
            "VERDICT_QUARANTINE" => Some(Self::Quarantine),
            "VERDICT_KILL" => Some(Self::Kill),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResponseMode {
    ResponseAuto = 0,
    ResponseConfirm = 1,
    ResponseMonitor = 2,
}
impl ResponseMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ResponseAuto => "RESPONSE_AUTO",
            Self::ResponseConfirm => "RESPONSE_CONFIRM",
            Self::ResponseMonitor => "RESPONSE_MONITOR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RESPONSE_AUTO" => Some(Self::ResponseAuto),
            "RESPONSE_CONFIRM" => Some(Self::ResponseConfirm),
            "RESPONSE_MONITOR" => Some(Self::ResponseMonitor),
            _ => None,
        }
    }
}
